### ISSUE TITLE
특이식/알러지 정보를 선택할 수 있다.

### ISSUE THREAD

**Issue by zionhann** [HGU-WALAB/dreamland-hackarton-front#2]
## Summary

사용자는 회원가입 직후 최초 1회에 한해 자신의 알러지 및 특이식 정보를 선택한다.

## Story Points

1H

## Tasks

- [ ] 알러지 종류 확인
- [ ] 관리할 특이식 종류 확인
- [ ] 특이식 선택시 관련된 알러지 종류 선별하여 데이터 전송
