### ISSUE TITLE
카테고리별 식품 목록을 조회할 수 있다.

### ISSUE THREAD

**Issue by zionhann** [HGU-WALAB/dreamland-hackarton-front#4]
## Summary

사용자는 지정된 카테고리에 해당하는 식품 목록을 확인할 수 있다.

## Story Points

1H

## Tasks

- [ ] 타겟 식품유형 데이터 생성
- [ ] 카테고리 컴포넌트 생성
- [ ] 카테고리 페이지 생성
